### ISSUE TITLE
Kanban view in edgeless mode can't be dragged left or right

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#4577] opened 2023-09-04 08:37 UTC

**Comment by Flrande** [comment] 2023-09-04 09:01
Can you share the screen recording?

**Comment by Flrande** [comment] 2023-09-04 09:02
I can't reproduce it. Can you share screen recording?

**Comment by Flrande** [comment] 2023-09-04 09:03
duplicate of #4578

**Closed by Flrande** 2023-09-04 09:03 UTC
