### ISSUE TITLE
Can't use arrow keys to transfer cursor and console error

### ISSUE THREAD

**Issue by m1911star** [toeverything/blocksuite#326] opened 2022-12-16 11:08 UTC
https://user-images.githubusercontent.com/4948120/208085455-d1c8be74-5fc6-48e2-87ed-3df81d44391c.mov

**Comment by doodlewind** [comment] 2022-12-16 13:23
The cursor issue looks like a regression, and the console error exists because the WebSocket signal server (used for initialization for WebRTC provider) was hard-coded to use localhost - can add some global server URLs as fallback, I think this already exists in codebase, just being commented out for now.

**Comment by himself65** [comment] 2022-12-16 17:30
I'm trying to fix cursor issue in https://github.com/toeverything/blocksuite/pull/327

**Comment by doodlewind** [comment] 2022-12-17 06:41
The console error should be fixed in [8a0e691](https://github.com/toeverything/blocksuite/commit/8a0e6917a78e7d256350c4e9a8a3dc188f6cef1d). Our team usually opens the playground page with `pnpm dev` started, guess that's why this was not noticed before.

**Comment by himself65** [comment] 2022-12-18 02:52
Landed in https://github.com/toeverything/blocksuite/commit/e1b2a90651b7365367e04598926e16fffe514df7

**Comment by doodlewind** [comment] 2022-12-18 03:37
I'm closing this @m1911star. Feel free to give feedback!

**Closed by doodlewind** 2022-12-18 03:37 UTC
Labels: bug
