### ISSUE TITLE
Pressing Delete key (not Backspace) in Windows keyboard does nothing

### ISSUE THREAD

**Issue by xell** [toeverything/blocksuite#3063] opened 2023-06-12 15:37 UTC
While selecting some blocks, pressing Delete key in a Windows keyboard does nothing instead of deleting the selection. However, Backspace key behaves as expected.

**Comment by doodlewind** [comment] 2023-06-13 01:20
Duplicate of #2550

**Closed** 2023-06-13 01:20 UTC
Labels: bug, beta
