### ISSUE TITLE
DeepScan failed

### ISSUE THREAD

**Issue by Himself65** [toeverything/blocksuite#538] opened 2023-01-04 14:42 UTC
https://deepscan.io/dashboard/#view=project&tid=19993&pid=23436&bid=711059&subview=pull-request&prid=1498906

**Comment by doodlewind** [comment] 2023-01-08 03:19
Closing and just removed DeepScan since the non-local-reproducible errors are very annoying :(

I'm open to stricter static checks, as long as they can have instant feedback directly in the IDE and won't block our workflow.

**Closed by doodlewind** 2023-01-08 03:19 UTC
Labels: bug
