### ISSUE TITLE
Support converting attachment card into link

### ISSUE THREAD

**Issue by PaxtonXuan** [toeverything/blocksuite#4084] opened 2023-08-15 07:51 UTC
https://github.com/toeverything/blocksuite/assets/134894293/946c6e2b-e418-447d-9874-49a3d7bde447

**Comment by doodlewind** [comment] 2023-08-16 01:10
You are not converting bookmark card, it's actually an attachment card. This is by design for now. Using link to represent attachment require more effort to develop.

**Comment by doodlewind** [comment] 2023-11-06 06:06
Closing as by design FTM.

**Closed by doodlewind** 2023-11-06 06:06 UTC
Labels: mod:custom-blocks, type:feat, story
