### ISSUE TITLE
Images can be converted into cards, but cards cannot be converted

### ISSUE THREAD

**Issue by YanxinLu0122** [toeverything/blocksuite#5097] opened 2023-10-24 02:53 UTC
https://github.com/toeverything/blocksuite/assets/144991896/a60cb8ec-12d3-44a4-9678-11daf1c2c528

**Comment by doodlewind** [comment] 2023-10-24 03:51
I think this is by design and undo/redo is supported in this case. The text here should not be "turn into card view" under the hood, but switching the block flavour from image to attachment.

**Comment by houjoe0829** [comment] 2023-10-25 06:23
Image, as the only attachment type that can currently be displayed in Embed View in the document, can be converted to Card View. It is also recommended to support the option to Turn into Embed View, which used to be interchangeable in previous designs. The visibility of the Undo shortcut key is not sufficient and requires a clear entry point. Currently, it is in the “Disable” state and cannot be clicked.
![CleanShot 2023-10-25 at 14 23 07@2x](https://github.com/toeverything/blocksuite/assets/22443345/8f1c44a2-7851-4fbb-94ca-fa8206185c2f)

**Comment by lawvs** [comment] 2023-10-25 15:46
It's a bug, I believe the inconsistency in implementation between the web and client versions of `BlobManager` caused this issue.

<img width="1278" alt="Screenshot 2023-10-25 at 23 44 45" src="https://github.com/toeverything/blocksuite/assets/18554747/65f093f5-d608-4a51-97aa-8e8a480f4474">

See https://github.com/toeverything/blocksuite/blob/9a92e4650d734d1cf05b6d2f66f4bbbbb5411c4a/packages/blocks/src/attachment-block/components/options.ts#L51

**Comment by doodlewind** [comment] 2024-01-29 02:25
Closed by #6069

**Comment by lawvs** [comment] 2024-01-29 03:54
This issue is caused by an inconsistency in implementation between the web and client, and can only be replicated on the client.

**Comment by EYHN** [comment] 2024-02-22 07:29
In the latest beta, this issue cannot be reproduced. Please try 0.12.0. If it can be reproduced, please reopen this issue again.

**Closed by EYHN** 2024-02-22 07:29 UTC
Labels: type:bug, mod:custom-blocks
