### ISSUE TITLE
AFFiNE Desktop 0.7.0-canary.0​ (Unable to Change First Column Type in Table)​​

### ISSUE THREAD

**Issue by purpleden** [toeverything/blocksuite#2794] opened 2023-05-26 12:46 UTC
### What happened?

Unable to change the column type on the first column (like the other columns)

![image](https://github.com/toeverything/AFFiNE/assets/33729019/f96013f7-e91a-43f0-b592-4bbd2ab90b6f)

Like this column:

![image](https://github.com/toeverything/AFFiNE/assets/33729019/c8fd7eba-6025-4fc4-ae84-447878a5333e)

### Version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zqran** [comment] 2023-05-29 02:33
This is because in our Database, the header column is a special column, which is different from the other columns that follow. Therefore, there are currently some restrictions on its operation.

**Comment by doodlewind** [comment] 2023-08-16 16:42
Closing this as by design :)

**Closed by doodlewind** 2023-08-16 16:42 UTC
Labels: type:bug
