### ISSUE TITLE
Use the scroll wheel to slide the page when dragging

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/blocksuite#4617] opened 2023-09-06 05:58 UTC
We can only support dragging to the bottom to move automatically under the page：

**Page mode：**

https://github.com/toeverything/blocksuite/assets/24713927/b9b2f006-9b6e-4485-aef5-571264894ad2

It would be more reasonable to support simultaneous dragging and scrolling actions

**Edgeless mode：**

edgeless mode is even worse, the scrolling will be offset when dragging：

https://github.com/toeverything/blocksuite/assets/24713927/1d016faa-0ce6-422d-bf3d-b42ed22cdf7a

**Comment by doodlewind** [comment] 2023-11-06 07:06
Closing as duplicate of #4561

**Closed by doodlewind** 2023-11-06 07:06 UTC
Labels: mod:edgeless, type:feat
