### ISSUE TITLE
Text-to-table view conversion - compatibility of the pop-up during text-to-table view conversion.

### ISSUE THREAD

**Issue by PaxtonXuan** [toeverything/blocksuite#4418] opened 2023-08-29 07:09 UTC
https://github.com/toeverything/blocksuite/assets/134894293/0482209e-8240-4c04-91ec-64957dfdbbf9

**Comment by zzj3720** [comment] 2023-08-29 08:14
This appears to be an older version of the view conversion UI
The new version looks like this
<img width="894" alt="image" src="https://github.com/toeverything/blocksuite/assets/17165520/97254ce0-a3d2-4d08-b800-141f26391a59">
And I fixed some bugs in this version, so you can wait for this one and check if the problem is still there!

**Comment by doodlewind** [comment] 2023-08-29 08:26
Closing since this seems to be fixed.

**Closed by doodlewind** 2023-08-29 08:26 UTC
Labels: type:bug, mod:database
