### ISSUE TITLE
Unable to delete contents

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/blocksuite#3710] opened 2023-07-26 03:09 UTC
https://user-images.githubusercontent.com/134897361/256101608-eacf0b51-d7ad-4eed-b31c-82bde4c68ad0.mp4

Neither you can delete key the contents, nor you can use backspace to delete the contents.

**Comment by doodlewind** [comment] 2023-07-26 08:26
Unable to reproduce on windows (0.7.0-beta), closing as a possible edge case.

**Closed by doodlewind** 2023-07-26 08:26 UTC
Labels: type:bug, reproduction needed, mod:block-selection
