### ISSUE TITLE
Support `virtual-text` component for GPT suggestion

### ISSUE THREAD

**Issue by himself65** [toeverything/blocksuite#3525] opened 2023-07-13 09:10 UTC
```ts
const block = page.getBlockById('xxx')

const virtualText = new VirtualText()
virtualText.updateText('Hello, world!')
virtualText.attach(block)

const block2 = page.getBlockById('yyy')
virtualText.updateText('This is copilot')
virtualText.attach(block2)
```

Only the user press `Tab` will insert the real text and yDoc, it is just a plain text, and only be shown at the end of text block

Example:

![image](https://github.com/toeverything/blocksuite/assets/14026360/8e7bb095-49e3-4e2b-8430-e711be5bacb0)

**Comment by Flrande** [comment] 2023-07-24 03:17
Will we need a "virtual block"? (the inferred text may have multiple paragraphs and each paragraphs is a block)

**Comment by doodlewind** [comment] 2023-07-24 16:08
Maybe we can define a temporary (and partial) block tree on top of AwarenessStore, merging its state with the YDoc-based one, just like what we do in edgeless LocalRecord.

In this way, every paragraph block can accept 2 data sources, one is the YText and the other one is the AwarenessStore (may be connected to LLM output stream). So a paragraph block can be rendered without assuming its data source is YDoc or AwarenessStore.

Not sure if this could do the trick.

**Comment by doodlewind** [comment] 2023-07-25 04:12
Closed as not in recent plan to support, since we've confirmed with @hwangdev97 that AFFiNE will use standalone modal for copilot drafting.

**Closed by doodlewind** 2023-07-25 04:12 UTC
Labels: roadmap, mod:rich-text, type:feat
