### ISSUE TITLE
Performance issue for large markdown content

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/blocksuite#4869] opened 2023-09-13 23:35 UTC
https://community.affine.pro/c/questions-answers/big-markdown-file-performance

**Comment by doodlewind** [comment] 2023-09-24 21:21
I would consider the `- # content` part as by design, so let's only track the performance issue here.

Regarding this, if you are not having one single lengthy code block (or one very long paragraph) in your large file, the performance should not be affected. We have tried on https://tiptap.dev/examples/book and most basic operations should be smooth. Will investigate if there are some regressions here.

**Comment by doodlewind** [comment] 2023-11-28 09:10
Closing since we are already using the `?init=heavy` preset for debugging perf issues, and basic operations opening the [tiptap/book](https://tiptap.dev/examples/book) example are basically fine. There are still certain operations that feels laggy in this scenario, further progress will be tracked in #5095.

**Closed by doodlewind** 2023-11-28 09:10 UTC
Labels: mod:infra, type:perf
