### ISSUE TITLE
Cannot delete any character using backspace in firefox

### ISSUE THREAD

**Issue by fourdim** [toeverything/blocksuite#3609] opened 2023-07-19 03:10 UTC
```
Uncaught TypeError: Intl.Segmenter is not a constructor
    handleDelete transform-input.ts:52
    transformInput transform-input.ts:177
    _onBeforeInput event.ts:341
37 transform-input.ts:52:27
```

**Comment by doodlewind** [comment] 2023-07-19 05:06
Duplicate of #3204, but I think we are only using `Intl.Segmenter` for manually selecting word range on double click. So a fallback shouldn't be hard to land.

**Closed** 2023-08-02 17:03 UTC
Labels: type:bug, mod:rich-text, compat, help wanted
