### ISSUE TITLE
Partial text copied within single line gets pasted as multiple blocks

### ISSUE THREAD

**Issue by DiamondThree** [toeverything/blocksuite#3153] opened 2023-06-16 09:43 UTC
### What happened?

![Utke4LCDCu](https://github.com/toeverything/AFFiNE/assets/24630517/20d62d7a-bdf2-414c-96e4-426b18499ce3)

### Distribution version

macOS x64

### What browsers are you seeing the problem on if you're using web version?

stable client

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment] 2023-06-18 15:25
Closing since I'm unable to reproduce this:

https://github.com/toeverything/blocksuite/assets/7312949/49e92760-0559-436e-af5c-ef74dcd56c4d

@DiamondThree please attach a reproducible recording or description of your operations (and feel free to reopen this issue by then!), otherwise it's hard to help with the fix.

**Comment by donteatfriedrice** [comment] 2023-06-18 16:08
> Closing since I'm unable to reproduce this:
> 
>  Screen.Recording.2023-06-18.at.23.20.07.mov 
> @DiamondThree please attach a reproducible recording or description of your operations (and feel free to reopen this issue by then!), otherwise it's hard to help with the fix.

This problem occurs when copying and pasting part of the text of blocks that have children blocks.
Steps to reproduce:
1. Create a block with children blocks.
2. Copy part of the text of the parent block.
3. Paste the content.

https://github.com/toeverything/blocksuite/assets/99816898/c09d7dd2-8b85-442d-bffd-39f4b54d60fd

**Comment by doodlewind** [comment] 2023-07-05 08:43
Fount this also worth investigating during our housekeeping stage, so /cc @zuoxiaodong0815 to take a look.

**Comment by zuoxiaodong0815** [comment] 2023-07-05 23:09
Please take time to fix this issue.  @fundon

**Comment by fundon** [comment] 2023-07-07 00:31
Why can't I find the event binding of `commnd+c`?

**Comment by zuoxiaodong0815** [comment] 2023-07-07 01:08
‘commnd+c’ triggers the browser copy event, and ‘commnd+v’ triggers the browser paste event

**Comment by fundon** [comment] 2023-07-07 01:24
> ‘commnd+c’ triggers the browser copy event, and ‘commnd+v’ triggers the browser paste event

 native selection need to check

**Comment by fundon** [comment] 2023-07-11 01:48
Trace it here, for the nested structure that wasn't handled properly.

https://github.com/toeverything/blocksuite/blob/0b07ee2d7d7efbe3f0b999672e2ffac2071268f6/packages/blocks/src/__internal__/clipboard/utils/commons.ts#L49-L61

**Comment by zuoxiaodong0815** [comment] 2023-07-11 02:05
Here it is written according to the previous data structure, you can adjust it according to the new structure. @fundon

**Comment by fundon** [comment] 2023-07-11 02:08
> Here it is written according to the previous data structure, you can adjust it according to the new structure. @fundon

Ok, trying.

**Closed** 2023-07-19 14:21 UTC
Labels: type:bug, mod:clipboard
