### ISSUE TITLE
The document sequence of bookmark unexpectedly changed after adding caption

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/blocksuite#4183] opened 2023-08-17 08:27 UTC

**Comment by Yanxi0202** [comment] 2023-08-17 08:30
Detailed video can not be uploaded, because of the length limited, will direct send to the responsible people through Feishu.

**Comment by doodlewind** [comment] 2023-08-17 08:32
If you are referring to this behavior, I guess it should be by design:

https://github.com/toeverything/blocksuite/assets/7312949/0acec876-7e78-4128-864a-91d0bbea9df7

**Comment by doodlewind** [comment] 2023-08-21 05:47
Closing since this is not reproduced in latest BlockSuite playground. If anyone encounters this, please let us know.

**Closed by doodlewind** 2023-08-21 05:47 UTC
Labels: type:bug, reproduction needed, mod:custom-blocks
