### ISSUE TITLE
Unexpected cursor position when undo markdown shortcut

### ISSUE THREAD

**Issue by Flrande** [toeverything/blocksuite#4377] opened 2023-08-25 13:45 UTC
https://github.com/toeverything/blocksuite/assets/50035259/59c3deeb-e37b-4ede-8af4-c25feab66cc2

The expected cursor should be after the space.

This bug is because the selection manager can't be updated when vRange changed but not apply range.

We need to update test related to inline markdown in `markdown.spec.ts` when we fix this bug.

**Comment by doodlewind** [comment] 2023-08-31 03:47
Duplicate of #3306

**Comment by Saul-Mirone** [comment] 2023-09-02 07:10
To fix this we need #4403 to be completed first. The solution would be similar to https://github.com/toeverything/blocksuite/pull/4555.

**Comment by Flrande** [comment] 2023-09-05 09:09
Will be fixed in #4605 but need to update tests.

**Comment by doodlewind** [comment] 2023-09-05 09:35
Duplicate of #4403

**Closed** 2023-09-11 01:31 UTC
Labels: type:bug, mod:cursor, mod:rich-text
