### ISSUE TITLE
When Switch to Edgeless Mode, the Title Will Be Lost

### ISSUE THREAD

**Issue by donteatfriedrice** [toeverything/blocksuite#2886] opened 2023-05-30 09:44 UTC
https://github.com/toeverything/blocksuite/assets/99816898/084abea4-1014-4d3b-8323-0512ebb3e21d

**Comment by doodlewind** [comment] 2023-05-31 08:09
This is currently by design since the edgeless editor is basically a whiteboard, and the title component is maintained in AFFiNE. But surely in our future version, we'll expose extensibility that allows more configurable stuff like this (see https://blocksuite.affine.pro/framework-integration.html but this unfinished yet). So I'd close this but feel free to discuss here :)

**Closed by doodlewind** 2023-05-31 08:09 UTC

**Comment by donteatfriedrice** [comment] 2023-05-31 08:19
> This is currently by design since the edgeless editor is basically a whiteboard, and the title component is maintained in AFFiNE. But surely in our future version, we'll expose extensibility that allows more configurable stuff like this (see https://blocksuite.affine.pro/framework-integration.html but this unfinished yet). So I'd close this but feel free to discuss here :)

Thanks for your response and for clarifying the current design.
