### ISSUE TITLE
Unable to view SVG images after upload

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#5089] opened 2023-10-23 09:09 UTC
The uploader can see the png/svg he uploaded, but the collaborator on the other side can only see the empty frame.

![Image](https://github.com/toeverything/blocksuite/assets/142964904/eae6489c-9082-4c34-a32e-6e3a3a24cb2f)

**Comment by YanxinLu0122** [comment] 2023-10-25 05:39
No just collaborator, all of the users in the page cannot see the svg images after uploaded.



https://github.com/toeverything/blocksuite/assets/144991896/1c66cd02-176b-49c2-b0b0-1f2facd232af

**Comment by Yuhang1015** [comment] 2023-11-03 06:16
still exist in 0.10.0 beta internal (https://github.com/toeverything/AFFiNE-Releases/releases/tag/0.0.0-internal.20231102154034-fb0aaab)


![Image](https://github.com/toeverything/blocksuite/assets/142964904/a5a7952a-e194-43dc-b85a-450bddf73b0e)

**Comment by doodlewind** [comment] 2023-11-03 07:34
Ping @Flrande to confirm if this could be reproduced 👀

**Comment by Flrande** [comment] 2023-11-05 09:23
I can only reproduce the issue successfully on the client, it works normally on the browser. Upon checking, I found that the indexedDB on the client has stored the svg data correctly. I suspect that the inability to display the image is related to the unique security restrictions on the client. cc @pengx17

**Comment by lawvs** [comment] 2023-11-05 13:07
This issue is also caused by https://github.com/toeverything/AFFiNE/issues/3245

The client identifies the type of the SVG blob as `application/octet-stream`, which is causing the error.

**Comment by doodlewind** [comment] 2023-11-06 09:34
Closed by https://github.com/toeverything/AFFiNE/pull/4845

**Closed by doodlewind** 2023-11-06 09:34 UTC
Labels: type:bug, mod:custom-blocks, fatal
