### ISSUE TITLE
Text Block cannot be directly dragged into Database

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/blocksuite#4591] opened 2023-09-05 00:09 UTC
<img width="901" alt="image" src="https://github.com/toeverything/AFFiNE/assets/5910926/e1cae521-c1df-45bf-8065-1145fb523d25">

**Comment by zzj3720** [comment] 2023-09-05 04:02
This issue will be resolved by implement #3366

**Comment by doodlewind** [comment] 2023-09-05 05:37
Duplicate of #3366

**Closed** 2023-09-05 14:52 UTC
