### ISSUE TITLE
​Empty content in exported file

### ISSUE THREAD

**Issue by NLBRT** [toeverything/blocksuite#2854] opened 2023-05-28 15:04 UTC
### What happened?

After exporting the file in both HTML and Markdown, when I open it, it's blank and displays no content. Upon further inspection, it seems to be that none of the contents are being actually saved in the exported file for some reason.

### Version

Windows x64

### Anything else?

Am I supposed to open the downloaded .exe everytime, or is it supposed to install the app to a default location?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment] 2023-05-30 03:09
@xell shall we add beta tag for this issue? @joebeijing has reproduced this on windows.

**Comment by NLBRT** [comment] 2023-05-30 10:07
> Hello, I wanna check that this version is for canary or beta? could you show us the version name/number for this bug?

@Yipei-Operation It's the Beta Client "20230518". Hope that helps.

**Comment by joebeijing** [comment] 2023-05-31 07:39
I can't reproduce it now after reinstalling the AFFiNE.  CC @doodlewind

**Comment by doodlewind** [comment] 2023-05-31 08:05
@NLBRT multiple members in our team have tried this on our new beta version on windows and seems that this is not reproduced FTM. So I'd close this as not reproduced. If you still encounter this issue after update this week (new beta comes tomorrow), please let us know, thanks! 🙏

**Closed by doodlewind** 2023-05-31 08:05 UTC
Labels: bug, reproduction needed, compat, mod:import-export, beta
