### ISSUE TITLE
Unable to duplicate using the slash menu action

### ISSUE THREAD

**Issue by fourdim** [toeverything/blocksuite#2788] opened 2023-05-26 16:03 UTC
Version: AFFiNE 0.5.4-beta.2
OS: Windows 10 22H2

To reproduce:

https://github.com/toeverything/blocksuite/assets/59462000/0cbd490d-c678-4585-8f7b-60e242734fba

**Comment by doodlewind** [comment] 2023-05-27 16:03
I think "duplicate" means copy+paste the current selected content, which is a convention on macOS (`cmd-D`). Using `cmd-V` to paste the previously copied content should work fine.

/cc @joebeijing how about adding a "Paste" entry in the slash menu actions?

**Comment by joebeijing** [comment] 2023-05-29 08:41
> I think "duplicate" means copy+paste the current selected content, which is a convention on macOS (`cmd-D`). Using `cmd-V` to paste the previously copied content should work fine.
> 
> /cc @joebeijing how about adding a "Paste" entry in the slash menu actions?

Paste was originally planned, but was removed due to browser limitations. It can be added back, but if the browser limitations cannot be solved, it needs to be changed to only visible to the client.

**Comment by houjoe0829** [comment] 2023-08-09 06:10
> As clipboard may contain sensitive information like passwords, it is dangerous for websites to access user's clipboard without requesting `clipboard-read` permission. Hence, browsers will ask for permissions by popping a prompt to ask for access (as we are not using native pasting options). It may be annoying for users to give permission for every paste. And an always allow option may be a security concern. See this issue for more: https://web.dev/i18n/en/async-clipboard/#security-and-permissions

Understood, that's why we set this option to be visible only to the client side.

**Comment by doodlewind** [comment] 2023-08-16 20:59
Closing as by design since the duplicate feature works in this way:

https://github.com/toeverything/blocksuite/assets/7312949/899b3004-1fc9-4661-adcc-33439272a453

**Closed by doodlewind** 2023-08-16 20:59 UTC
Labels: type:bug, mod:clipboard
