### ISSUE TITLE
After the whiteboard layout, switch back to the document, and then switch to the whiteboard again, and the layout will be lost

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/blocksuite#2535] opened 2023-05-11 08:41 UTC
https://github.com/toeverything/blocksuite/assets/5910926/7bb33c17-f26b-4708-abef-f244d4a0acd4

[三国志18_B-lsje-3n5.db.zip](https://github.com/toeverything/blocksuite/files/11450156/18_B-lsje-3n5.db.zip)

**Comment by doodlewind** [comment] 2023-05-11 09:12
Duplicate of #2479

**Closed by doodlewind** 2023-05-11 09:12 UTC
