### ISSUE TITLE
language

### ISSUE THREAD

**Issue by Luckstarnlj** [toeverything/blocksuite#5872] opened 2023-12-27 06:42 UTC
Does it not support internationalization？

**Comment by doodlewind** [comment] 2023-12-27 07:39
Closing as duplicate of #1296 (will be tracked there). For now we can support certain block-level config (e.g., customizing placeholder for paragraph block), but the goal for the BlockSuite framework is to allow developers building your own widgets, so it'll be up to widget implementation to support i18n. For current default widgets in `DocEditor` and `EdgelessEditor`, it's in longer term plan for the i18n support.

**Closed by doodlewind** 2023-12-27 07:39 UTC
Labels: mod:widget, type:feat
