### ISSUE TITLE
Dragging items in Block Hub to the body text causes a delay in the positioning of the guide lines

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#1577] opened 2023-03-08 13:59 UTC
https://user-images.githubusercontent.com/22443345/223731988-6da34129-70c2-4743-b898-f228a0a745ea.mp4

**Comment by doodlewind** [comment] 2023-03-09 02:52
Duplicate of https://github.com/toeverything/AFFiNE/issues/1224

**Closed by doodlewind** 2023-03-09 02:52 UTC
Labels: bug
