### ISSUE TITLE
Incorrect note block height

### ISSUE THREAD

**Issue by kemalakcc** [toeverything/blocksuite#5060] opened 2023-10-18 16:50 UTC
### What happened?

Here is a gif:

![main_large](https://github.com/toeverything/blocksuite/assets/7312949/347eac9a-4b4c-485d-a1b2-50e8a22c7b3c)

It seems after a size limit is exceeded, drag and drop starts to work only from the header. You can't grab the block from the bottom or sides.

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment] 2023-10-19 03:36
This sources from incorrect note block height, @kemalakcc could you share about how to reproduce the state before dragging?

**Comment by kemalakcc** [comment] 2023-10-19 03:41
I just put a very big image (a screenshot of my two monitors). I also tested it with different big images. The issue is fixed if you shrink this container size. And reoccurs if you make it bigger again. So I believe you can reproduce it with any image but resizing it to a bigger size

**Comment by doodlewind** [comment] 2023-11-28 09:11
Closing since we've supported https://github.com/toeverything/blocksuite/pull/5337 that allows you to set note size and make it collapsible, but the auto height feature for note block should also work.

**Closed by doodlewind** 2023-11-28 09:11 UTC
Labels: type:bug, reproduction needed, mod:edgeless
