### ISSUE TITLE
Cannot type in note of the first editor when using multiple-editor in playground

### ISSUE THREAD

**Issue by donteatfriedrice** [toeverything/blocksuite#5425] opened 2023-11-24 03:34 UTC
https://github.com/toeverything/blocksuite/assets/99816898/4568d294-c18d-4f8a-b762-2c16fc82a1d6

**Comment by AyushAgrawal-A2** [comment] 2023-11-26 05:55
duplicate of #5153

**Closed by AyushAgrawal-A2** 2023-11-26 05:55 UTC
Labels: type:bug, mod:edgeless, mod:rich-text
