### ISSUE TITLE
Test cases is not working in debug mode with Playwright VSCode extension 

### ISSUE THREAD

**Issue by lawvs** [toeverything/blocksuite#2735] opened 2023-05-24 08:52 UTC
Related to https://github.com/toeverything/blocksuite/issues/2492 @zzj3720 

<img width="1114" alt="Screenshot 2023-05-24 at 4 51 53 PM" src="https://github.com/toeverything/blocksuite/assets/18554747/96cec4eb-d9bb-4fed-b47d-3a5b8875c7ef">

<img width="937" alt="Screenshot 2023-05-24 at 4 16 26 PM" src="https://github.com/toeverything/blocksuite/assets/18554747/7f081ee4-9856-4081-8e43-a09f0b59d650">

**Comment by doodlewind** [comment] 2023-05-24 10:02
Unable to reproduce locally:

<img width="800" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/944e3e19-6f0e-4faf-a89c-290d54a5e7a8">

**Comment by doodlewind** [comment] 2023-06-05 02:21
Closed as not reproduced in current local environment.

**Closed by doodlewind** 2023-06-05 02:21 UTC
Labels: mod:infra, test
