### ISSUE TITLE
Sometimes when double-clicking will result in a textContent error

### ISSUE THREAD

**Issue by alt1o** [toeverything/blocksuite#2273] opened 2023-04-25 07:47 UTC
https://user-images.githubusercontent.com/21084335/234209523-8581a9ba-cef5-4065-8351-8d9a7e6fd351.mov

**Comment by alt1o** [comment] 2023-04-25 07:49
In this case, the selection's `anchorNode` is the comment node. We should find the correct text node. Maybe this is function is helpful https://github.com/toeverything/blocksuite/blob/33c2000afbabad8933ec75b4dd42f29489217778/packages/virgo/src/utils/point-conversion.ts#L7-L8  by @Flrande

**Comment by doodlewind** [comment] 2023-05-29 19:24
Closing since this is not reproduced in latest master. This should be related to #1471 and possibly fixed by #2474

**Closed by doodlewind** 2023-05-29 19:24 UTC
Labels: bug, mod:cursor, help wanted
