### ISSUE TITLE
After selecting text, typing on the keyboard should directly replace the selected text

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#2514] opened 2023-05-10 14:08 UTC
(from Azure)

**Comment by xell** [comment] 2023-05-11 02:17
In a certain sense, this is related with #2433, both of which means that the input event should consider the existed selection.

**Comment by doodlewind** [comment] 2023-05-11 02:31
Duplicate of #2433

**Closed by doodlewind** 2023-05-11 02:31 UTC
Labels: feat, story
