### ISSUE TITLE
Hiding objects on page mode will remove background

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/blocksuite#3508] opened 2023-07-13 02:56 UTC
This object and the colour changes are only visible in Edgeless so it doesn't seem to make much sense that if you change to "hidden from Page mode" that the formatting is lost.

https://user-images.githubusercontent.com/4605025/253146586-035b3faf-6d2c-418c-b05c-67a60e0bd976.mov

**Comment by Flrande** [comment] 2023-07-13 07:50
It is by design to differentiate. cc @hwangdev97

**Comment by doodlewind** [comment] 2023-07-13 08:04
Closing as by design according to current requirement.

**Closed by doodlewind** 2023-07-13 08:04 UTC
Labels: type:bug, mod:edgeless, beta
