### ISSUE TITLE
Lose All Characters After HTML Tags

### ISSUE THREAD

**Issue by sxzz** [toeverything/blocksuite#2453] opened 2023-05-08 12:31 UTC
1. https://blocksuite-toeverything.vercel.app/?init=empty
2. Type `test <script> hello`
3. Copy the paragraph, and paste it to a rich text editor (like Typora, Notion, [Tiptap](https://tiptap.dev/examples/default), [HeteroDoc](https://heterodoc.netlify.app/))
4. Only `test ` left

---

And paste it into Twitter's editor, we'll get
```
test  hello</p><blocksuite style="display: none" data-type="blocksuite/page" data-clipboard="[{&quot;flavour&quot;:&quot;affine:paragraph&quot;,&quot;type&quot;:&quot;text&quot;,&quot;text&quot;:[{&quot;insert&quot;:&quot;test <script> hello&quot;}],&quot;children&quot;:[]}]"></blocksuite>
```

**Comment by QiShaoXuan** [comment] 2023-05-09 05:17
The cause of this bug is that the copied information is not processed with tag-like text, causing an error in parsing the html when pasting

**Comment by QiShaoXuan** [comment] 2023-05-09 05:18
Fixed in https://github.com/toeverything/blocksuite/pull/2463

**Closed** 2023-05-09 05:26 UTC
Labels: bug, mod:clipboard, fatal, help wanted
