### ISSUE TITLE
Content lost after pasting during collaboration

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/blocksuite#4799] opened 2023-09-18 02:41 UTC
Cloud collaborative testing can be frustrating when you encounter an error after copying and pasting a large amount of content, and then refresh the page only to find that the content is lost.

[Slack Message](https://affine-pro.slack.com/archives/C05QRGNFWUW/p1694142326209389?thread_ts=1694142326.209389&cid=C05QRGNFWUW)

**Comment by hwangdev97** [comment] 2023-09-18 02:42
![image](https://github.com/toeverything/blocksuite/assets/24713927/3b62bee1-cf14-4a85-bd64-37eb79e1ad88)

**Comment by doodlewind** [comment] 2023-09-18 19:01
Possibly duplicate of #4779

**Comment by fourdim** [comment] 2023-09-18 19:06
Trace it here. It looks like it's because of the selection lost.
https://github.com/toeverything/blocksuite/blob/master/packages/blocks/src/__internal__/clipboard/page-clipboard.ts#L60-L66

**Comment by fourdim** [comment] 2023-09-18 19:35
It's possibly because you are focusing on the side panel rather than the editor causing no cursor presented at the editor.
As a result, the editor does not know where to paste.
Could you please check if you are under this circumstance?

**Comment by fourdim** [comment] 2023-10-10 01:01
Errors here are resolved by #4975.
However, the errors are not related to this issue.

**Comment by fourdim** [comment] 2023-10-23 23:09
Stop investigating.

**Closed by fourdim** 2023-10-23 23:09 UTC
Labels: type:bug, reproduction needed, mod:import-export
