### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'getTextNodesFromElement')

### ISSUE THREAD

**Issue by BedBear** [toeverything/blocksuite#2155] opened 2023-04-19 04:31 UTC
When I
`import { SimpleAffineEditor } from '@blocksuite/editor';`

It shows
<img width="955" alt="image" src="https://user-images.githubusercontent.com/8636635/232967226-efe761ca-7d58-4bae-ad9c-abd6b9a89e70.png">

My dependencies
`
"@blocksuite/blocks": "^0.0.0-20230418192708-038c287a-nightly",
"@blocksuite/editor": "^0.0.0-20230418192708-038c287a-nightly",
"@blocksuite/store": "^0.0.0-20230418192708-038c287a-nightly",`

**Comment by BedBear** [comment] 2023-04-19 05:14
When I install dependencies
`
"@blocksuite/blocks": "^0.5.0-alpha.3",
    "@blocksuite/editor": "^0.5.0-alpha.3",
    "@blocksuite/store": "^0.5.0-alpha.3",
`

It shows
<img width="931" alt="image" src="https://user-images.githubusercontent.com/8636635/232973118-5f0580ed-dcb7-42e0-9d54-37e73d8e4d72.png">

**Comment by XvHaidong** [comment] 2023-04-19 07:52
+1

**Comment by zqran** [comment] 2023-04-19 09:46
> When I install dependencies `"@blocksuite/blocks": "^0.5.0-alpha.3", "@blocksuite/editor": "^0.5.0-alpha.3", "@blocksuite/store": "^0.5.0-alpha.3",` and import SimpleAffineEditor `import { SimpleAffineEditor } from '@blocksuite/editor';`

@BedBear 
I tried to reproduce this bug in the project created by vite, but it didn't reproduce. Can you provide more information?

**Comment by BedBear** [comment] 2023-04-19 14:45
When I installed the following version, the problem disappeared.
`
"@blocksuite/blocks": "^0.0.0-20230412114309-05fc8eec-nightly",
"@blocksuite/editor": "^0.0.0-20230412114309-05fc8eec-nightly",
"@blocksuite/react": "^0.0.0-20230412114309-05fc8eec-nightly",
`

**Comment by BedBear** [comment] 2023-04-19 14:49
> > When I install dependencies `"@blocksuite/blocks": "^0.5.0-alpha.3", "@blocksuite/editor": "^0.5.0-alpha.3", "@blocksuite/store": "^0.5.0-alpha.3",` and import SimpleAffineEditor `import { SimpleAffineEditor } from '@blocksuite/editor';`
> 
> @BedBear I tried to reproduce this bug in the project created by vite, but it didn't reproduce. Can you provide more information?

"dependencies": {
    "@ant-design/icons": "^5.0.1",
    "@blocksuite/blocks": "^0.0.0-20230412114309-05fc8eec-nightly",
    "@blocksuite/editor": "^0.0.0-20230412114309-05fc8eec-nightly",
    "@blocksuite/react": "^0.0.0-20230412114309-05fc8eec-nightly",
    "@blocksuite/store": "^0.0.0-20230412114309-05fc8eec-nightly",
    "@craco/craco": "^7.1.0",
    "@douyinfe/semi-ui": "^2.32.2",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "antd": "^5.3.2",
    "date-fns": "^2.29.3",
    "dexie": "^3.2.3",
    "history": "^5.3.0",
    "next": "^13.3.0",
    "react": "^18.2.0",
    "react-dnd": "^16.0.1",
    "react-dnd-html5-backend": "^16.0.1",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.10.0",
    "react-scripts": "5.0.1",
    "slate": "^0.93.0",
    "slate-react": "^0.93.0",
    "web-vitals": "^2.1.4"
  },

**Comment by BedBear** [comment] 2023-04-21 15:55
I used the code from your example and encountered the same error. Even when I commented out the other three lines and only kept the first line `import { SimpleAffineEditor } from '@blocksuite/editor';`, the error still occurred. 
I think there may be an issue with the package version "@blocksuite/editor": "^0.0.0-20230418192708-038c287a-nightly". I did not encounter any errors when I used the package version "@blocksuite/editor": "^0.0.0-20230412114309-05fc8eec-nightly".

**Comment by zqran** [comment] 2023-04-22 02:14
> I used the code from your example and encountered the same error. Even when I commented out the other three lines and only kept the first line `import { SimpleAffineEditor } from '@blocksuite/editor';`, the error still occurred. I think there may be an issue with the package version "@blocksuite/editor": "^0.0.0-20230418192708-038c287a-nightly". I did not encounter any errors when I used the package version "@blocksuite/editor": "^0.0.0-20230412114309-05fc8eec-nightly".

Since BlockSuite is under heavy development, we recommend you to use the latest nightly version.

**Comment by zqran** [comment] 2023-04-24 12:27
@BedBear
I will close this issue, if you encounter other problems, please provide more information. Thanks for your feedback.

**Closed by zqran** 2023-04-24 12:27 UTC
Labels: bug, mod:infra, help wanted
