### ISSUE TITLE
Bookmarks are no longer loading

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/blocksuite#3541] opened 2023-07-14 06:41 UTC
Bookmarks preview do not load - infinite loading phase

![Image](https://user-images.githubusercontent.com/4605025/253492531-cc54f5dd-f6bc-4456-8259-bbe0f3e3e4d7.png)

**Comment by doodlewind** [comment] 2023-07-14 06:53
This is reproduced in latest internal (but not BlockSuite playground). Require @QiShaoXuan to take a look.

**Comment by QiShaoXuan** [comment] 2023-07-14 06:54
Has fixed in https://github.com/toeverything/AFFiNE/pull/3226, same as https://github.com/toeverything/AFFiNE/issues/3227

**Comment by doodlewind** [comment] 2023-07-14 06:56
@QiShaoXuan this is not included in https://github.com/toeverything/AFFiNE-Releases/releases/tag/0.0.0-internal.20230714053343-27fa565 release, maybe this require another internal release?

**Comment by QiShaoXuan** [comment] 2023-07-14 07:01
> @QiShaoXuan this is not included in https://github.com/toeverything/AFFiNE-Releases/releases/tag/0.0.0-internal.20230714053343-27fa565 release, maybe this require another internal release?

Yes, it need to rebuild a new internal release

**Comment by QiShaoXuan** [comment] 2023-07-14 07:02
I think this issue should be closed after new internal version deploy

**Comment by doodlewind** [comment] 2023-07-14 07:04
@QiShaoXuan never mind, it's good to close this since you have landed the fix. We should do the verify process using other GitHub project fields.

**Closed by doodlewind** 2023-07-14 07:04 UTC
Labels: type:bug, mod:custom-blocks
