### ISSUE TITLE
Bug while exporting Edgeless mode content​

### ISSUE THREAD

**Issue by Soliprem** [toeverything/blocksuite#5214] opened 2023-11-06 07:20 UTC
### What happened?

![image](https://github.com/toeverything/AFFiNE/assets/73885403/3eab64fc-ba21-454c-bedf-1ab95c62965e)
This is a project I've been working on
![Macroeconomics-1](https://github.com/toeverything/AFFiNE/assets/73885403/62bae018-5ab2-4fa3-80d2-35a5484d6c90)
,
[Macroeconomics.pdf](https://github.com/toeverything/AFFiNE/files/13263632/Macroeconomics.pdf)
and these are the result of exporting it. As you can see, both have pretty serious text formatting issues, and the pdf is in B&W

### Distribution version

Linux

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by fourdim** [comment] 2023-11-07 05:16
Could you please tell me which version are you working on? Including the version of AFFiNE and where do you get the AFFiNE (e.g. AUR, nixpkgs).

**Comment by Soliprem** [comment] 2023-11-29 19:38
sorry, I missed the notifications: I'm using the AUR version off Affine. I'll check later on when I have the project on-hand to see if the bug is still present

**Comment by fourdim** [comment] 2023-11-29 23:40
Sure. You can also copy it to the [blocksuite playground](https://blocksuite-toeverything.vercel.app/), click on Menu -> Test Operations -> Export Snapshot and then upload the snapshot to here.
It's possibily because of [ligature](https://en.wikipedia.org/wiki/Ligature_(writing)), if fonts on your computer does not support this, it will just fall back to other fonts which results in the bug.
But still, we need a snapshot to reproduce this and then investigate the real root cause.

**Comment by Soliprem** [comment] 2023-11-30 12:36
My font does not, in fact, support ligatures (it's the one gripe I have with it, it's SauceCodePro Nerd Font)

**Comment by doodlewind** [comment] 2024-01-22 05:34
Should be closed by #5945, please checkout current AFFiNE canary or beta to see if it's fixed.

**Closed by doodlewind** 2024-01-22 05:34 UTC
Labels: type:bug, mod:edgeless, mod:import-export
