### ISSUE TITLE
​In the tips placeholder, the highlight icon will make it look like it can be clicked

### ISSUE THREAD

**Issue by rottenpen** [toeverything/blocksuite#2851] opened 2023-04-27 01:14 UTC
### Description

<img width="477" alt="image" src="https://user-images.githubusercontent.com/12029924/234734689-a1640688-3e98-4cc6-a057-e501cb16e3c7.png">

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by joebeijing** [comment] 2023-05-30 05:46
Currently, this area is working as intended. Our goal is to indicate that it is clickable when it is hovering, without being too distracting and taking editors' attention away from their work.

**Comment by doodlewind** [comment] 2023-05-30 05:59
Closing as working as expected, cheers!

**Closed by doodlewind** 2023-05-30 05:59 UTC
Labels: feat, story, beta
