### ISSUE TITLE
Note state is stale and doesn't follow selection rect in collaboration

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#4703] opened 2023-09-11 07:58 UTC
When editing new content in edgeless mode, collaboration can only be seen by refreshing or turning to page mode and then returning to edgeless mode.

https://toeverything.feishu.cn/minutes/obcnh1rw733wwavi2821k5e8

**Comment by fourdim** [comment] 2023-09-12 00:43
It's probably network issue or server's issue. I cannot reproduce it in the blocksuite playground. Could you please press the hotkey  `Ctrl+Shift+I`, toggle to the console panel, and paste logs here?
BTW, you can paste the video to github by just copying the video file and press `ctrl+v` in the input box.

**Comment by Yuhang1015** [comment] 2023-09-12 06:50
Sorry for the inconvenience, maybe it was a network problem yesterday. I uploaded the video by dragging and dropping or adding attachments, but all failed, so I could only choose to upload the feishu link. I have re-uploaded all the videos today. If the video upload fails again next time, I will record it in time.



https://github.com/toeverything/blocksuite/assets/142964904/ab9e320b-3534-42f6-9b7f-c3b244d03523

**Comment by doodlewind** [comment] 2023-09-14 03:06
Possible duplicate of #4697

**Comment by fourdim** [comment] 2023-09-18 23:12
Closed by #4808.

**Closed by fourdim** 2023-09-18 23:12 UTC
Labels: type:bug, reproduction needed, mod:edgeless, mod:store, fatal
