### ISSUE TITLE
Pasted frame in edgeless mode will disappear when blur

### ISSUE THREAD

**Issue by rottenpen** [toeverything/blocksuite#2567] opened 2023-05-15 01:59 UTC
https://github.com/toeverything/blocksuite/assets/12029924/1bf15a44-1a49-4d0f-aedf-ed422c691206

**Comment by doodlewind** [comment] 2023-05-15 02:33
There was a piece of code that automatically removes empty frame on blur (since this frame may come from the `T` tool in the edgeless toolbar). Does this happen for non-empty frame?

Also, it would be great if you can use an app like KeyCastr that visualizes your key stroke :D

<img width="184" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/925f991a-79db-45ff-ae7d-11208f3415fb">

**Comment by doodlewind** [comment] 2023-05-29 19:44
Closing since this looks to be the expected behavior currently. For non-empty blocks, it should be kept after the focus blurs.

**Closed by doodlewind** 2023-05-29 19:44 UTC
Labels: bug, mod:edgeless
