### ISSUE TITLE
Images should support long press to directly drag and adjust the sorting

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#3119] opened 2023-06-15 05:38 UTC
https://github.com/toeverything/blocksuite/assets/22443345/c9a55671-4774-4de3-9293-5bfa1332430d

1. The current behavior is that the first drag and drop does not work, but after the first attempt, the images can be dragged and dropped.
2. Also, the cursor should change to a hand gesture when hovering over the image, indicating that it can be dragged and dropped.

**Comment by doodlewind** [comment] 2023-08-16 20:44
Duplicate of #4023 #2580

**Closed** 2023-09-21 13:01 UTC
Labels: type:bug, mod:custom-blocks
