### ISSUE TITLE
The toolbar of note within the edgeless mode can only move right

### ISSUE THREAD

**Issue by PaxtonXuan** [toeverything/blocksuite#3576] opened 2023-07-17 06:16 UTC
https://github.com/toeverything/blocksuite/assets/134894293/0a99f5f2-c32a-4bff-801a-b9c8bd2d9504

**Comment by donteatfriedrice** [comment] 2023-07-17 06:59
this issue seems to be a duplicate of #3570

**Comment by hwangdev97** [comment] 2023-07-17 08:28
this issue is duplicated, we will use #3570  to track this problem

**Closed by hwangdev97** 2023-07-17 08:28 UTC
Labels: type:bug, mod:edgeless
