### ISSUE TITLE
When collaborating, if one person drags content, others can only see the empty frame being moved

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#4778] opened 2023-09-15 08:26 UTC
![Image](https://user-images.githubusercontent.com/142964904/268222907-64b445f2-de93-4ba7-a635-4390ed306a38.gif)

**Comment by donteatfriedrice** [comment] 2023-09-15 08:46
duplicate of #4697

**Comment by Saul-Mirone** [comment] 2023-09-19 08:19
Closed by https://github.com/toeverything/blocksuite/pull/4808

**Closed by Saul-Mirone** 2023-09-19 08:19 UTC
Labels: type:bug, mod:edgeless
