### ISSUE TITLE
Support updating connected block after using block slicer

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/blocksuite#4332] opened 2023-08-24 07:41 UTC
https://github.com/toeverything/blocksuite/assets/134897361/7a2004f7-2f19-47c5-8720-8d4c3b949ff3

details: after used the block slicer, the connector should follow up with the previous content block (at the bottom) instead of following the front block.

**Comment by doodlewind** [comment] 2024-01-22 05:49
Closing since semantically the connector should be kept connected to the base note block. Reconnecting the connector to newly sliced block manually is also confirmed to work.

**Closed by doodlewind** 2024-01-22 05:49 UTC
Labels: mod:edgeless, type:feat, story
