### ISSUE TITLE
Linked pages inserted in a list should be displayed in the Page Tree

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#3969] opened 2023-08-11 03:14 UTC
In all other cases, it functions normally.
![CleanShot 2023-08-11 at 11 10 08@2x](https://github.com/toeverything/blocksuite/assets/22443345/d6729252-1dfe-4d5a-8314-c58bc655a249)

**Comment by pengx17** [comment] 2023-08-11 10:10
Duplicate of https://github.com/toeverything/AFFiNE/issues/3660

**Closed** 2023-08-11 10:11 UTC
Labels: type:bug, mod:link
