### ISSUE TITLE
Can not scroll to end when select last image by drag handle

### ISSUE THREAD

**Issue by lawvs** [toeverything/blocksuite#3613] opened 2023-07-19 07:19 UTC
## Reproduce step

- Paste an image at the end of the editor
- Select the image by drag handler
- Scroll to top
- Try scroll to end

https://github.com/toeverything/blocksuite/assets/18554747/da0cb307-e0d3-4845-9931-443ab9497296

**Comment by zhengjitf** [comment] 2023-07-21 13:51
https://github.com/toeverything/blocksuite/blob/0193726ad5c468366ef5014ee13f941af68fa312/packages/blocks/src/page-block/default/default-page-block.ts#L301-L329

FYI: The problem is that the `viewport` object is not updated after inserting an image, line 314 will get old values, finally set `scrollTop` incorrectly. 

A preliminary idea is that observing pageBlockContainer to update viewport.

```diff
  private _initResizeEffect() {
    const resizeObserver = new ResizeObserver(
      (entries: ResizeObserverEntry[]) => {
        for (const { target } of entries) {
          if (target === this.viewportElement) {
            this.selection?.updateViewport();
            this.selection?.updateRects();
            break;
          }

+         if (target === this.pageBlockContainer) {
+            this.selection?.updateViewport();
+            break;
+         }
        }
      }
    );
    resizeObserver.observe(this.viewportElement);
+   resizeObserver.observe(this.pageBlockContainer);
    this._resizeObserver = resizeObserver;
  }
```

I'm planning to investigate further and fix it within the next two days. Could you please assign it to me? @doodlewind

**Comment by doodlewind** [comment] 2023-07-21 13:52
Sure, much thanks for your participation!

**Closed** 2023-07-24 08:27 UTC
Labels: mod:infra, mod:block-selection, help wanted
