### ISSUE TITLE
The prompt word of the picture function key is behind the interface.

### ISSUE THREAD

**Issue by aiyou9** [toeverything/blocksuite#3797] opened 2023-06-09 20:07 UTC
### What happened?

![image](https://github.com/toeverything/AFFiNE/assets/15712822/e3ea43b3-8743-40bd-8a3f-88facfc2beb6)

### Version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment] 2023-08-08 04:07
Require @lawvs to evaluate, the official team should take over the maintenance in this iteration. Thanks.

**Comment by lawvs** [comment] 2023-08-08 07:36
Also related to https://github.com/toeverything/blocksuite/issues/3745

**Comment by doodlewind** [comment] 2023-08-16 07:51
Duplicate of #3744

**Closed by doodlewind** 2023-08-16 07:51 UTC
Labels: type:bug, good first issue, mod:ui-style
