### ISSUE TITLE
The slash menu is not appearing in other application as in the playground

### ISSUE THREAD

**Issue by HabibullahFTL** [toeverything/blocksuite#6317] opened 2024-02-28 07:24 UTC
Hello BlockSuite team,
I've tested the slash menu, is not working as appears in the Affine editor and BlockSuite playground. 
For your better understanding, I am including here my test codes & deployed links-
Live link: https://next-ts-blocksuite.vercel.app/
Github repo: https://github.com/HabibullahFTL/next-ts-blocksuite
BS editor implementation: https://github.com/HabibullahFTL/next-ts-blocksuite/blob/main/components/TestBlockSuite.jsx

**Comment by doodlewind** [comment] 2024-02-28 07:35
https://github.com/toeverything/blocksuite/assets/7312949/3466447b-db01-49a0-aa4f-66a6daf63da7

Thanks for your feedback. Tried the playground you deployed but the slash menu seems to be working, any reproduction steps?

**Comment by HabibullahFTL** [comment] 2024-02-28 07:39
@doodlewind , I've observed that certain options such as YouTube, Figma, GitHub, and Loam embeddings are not available in the slash menu when utilizing BlockSuite by creating an instance of new DocEditor(). However, these options are accessible in the BlockSuite playground.

**Comment by doodlewind** [comment] 2024-02-28 08:01
Should be fixed by #6319, also cc @Flrande to make the slash menu items configurable per-block spec (should be in our recent plan).

**Closed** 2024-02-28 08:05 UTC
Labels: type:bug, mod:widget

**Comment by HabibullahFTL** [comment] 2024-02-28 08:38
@doodlewind , I'm curious about the timeline for the next BlockSuite version release and when we can expect the new options to be available. Any insight you can provide would be helpful for my planning.

**Comment by doodlewind** [comment] 2024-02-28 08:42
@HabibullahFTL you can use the `blocksuite@canary` versions by tomorrow. The next `0.13` version is planned to be released at about next week (it's a special minor version bump, since there are mainly API naming changes in #6290). Regularly we release a minor version every 6 weeks.

**Comment by HabibullahFTL** [comment] 2024-02-28 08:49
Thank you.
