### ISSUE TITLE
Extend support for page properties/tags

### ISSUE THREAD

**Issue by chinnuu05** [toeverything/blocksuite#5551] opened 2023-12-02 02:58 UTC
It would be nice if pages could have multiple nameable properties in addition to the tag system we have now. 

Kind of like the property system Notion has for databases, this way pages can have more than one field. 

Ex: use case for writing: author tag, category tag, etc

Any plans to support this or add the ability to customize? If not I'm interested in contributing and making it happen.

**Comment by doodlewind** [comment] 2023-12-04 05:43
Thanks for the feedback! This looks to be duplicate of #4400 and due to the recent shift of focus, we've added a collection issue for database related feature requests. This is recorded and will be scheduled afterwards. Let's track this in https://github.com/toeverything/blocksuite/issues/5385.

**Closed by doodlewind** 2023-12-04 05:43 UTC
Labels: mod:database, type:feat
