### ISSUE TITLE
AFFiNE Desktop 0.7.0-canary.0​ (Allow Snapping in Edgeless Mode?)​

### ISSUE THREAD

**Issue by purpleden** [toeverything/blocksuite#2797] opened 2023-05-26 12:51 UTC
### Description

In edgeless mode, it'd be great to see a snapping feature to the guide dots instead of freehand

![image](https://github.com/toeverything/AFFiNE/assets/33729019/813cf48d-baca-41f2-aa16-f5007dfcd0d9)

### Use case

Make it easier to drag blocks and snap together

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment] 2023-05-29 19:47
Closing this as duplicate of #2440, but no worries, we are planning and will be actively working on this!

**Closed by doodlewind** 2023-05-29 19:47 UTC
Labels: mod:edgeless, feat, story
