### ISSUE TITLE
Support gantt and calendar view

### ISSUE THREAD

**Issue by Ikki-Dai** [toeverything/blocksuite#5558] opened 2023-12-03 00:24 UTC
### Description

will the table have a gantt and calendar view like notaion、flowus and lark

### Use case

 notaion、flowus and lark

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment] 2023-12-04 05:44
Thanks for the feedback! This seems to be duplicate of #2172 and due to the recent shift of focus, we've added a collection issue for database related feature requests. This is recorded and will be scheduled afterwards. Let's track this in https://github.com/toeverything/blocksuite/issues/5385.

**Closed by doodlewind** 2023-12-04 05:44 UTC
Labels: mod:database, type:feat
