### ISSUE TITLE
LanguageTool spell checker doesn't work in blocksuite

### ISSUE THREAD

**Issue by AlessioGr** [toeverything/blocksuite#1901] opened 2023-03-30 11:13 UTC
https://user-images.githubusercontent.com/70709113/228818646-f989313d-1263-4ab6-9340-b4bca01ece25.mp4

See video. LanguageTool is a grammar/spell checker. It works in pretty much all editors, but duplicates the text in blocksuite. It would be great if you can make sure spell checkers like LanguageTool are supported.

This happens in both edgeless and normal mode.

**Comment by Flrande** [comment] 2023-03-31 04:17
It seems to be working properly on my computer. What browser are you using?

https://user-images.githubusercontent.com/50035259/229021420-ba7d5983-1ac6-400b-8851-eece33e76a26.mp4

**Comment by zuozijian3720** [comment] 2023-04-20 14:27
I think this may be because LanguageTool changes the text immediately when setting the "selection".
In this case, "selectionchange" will not be triggered. So vRange is wrong when trigger "beforeinput"
I can commit a PR to check if this is the cause.

**Comment by Flrande** [comment] 2023-04-20 14:29
> I think this may be because LanguageTool changes the text immediately when setting the "selection".
> In this case, "selectionchange" will not be triggered. So vRange is wrong when trigger "beforeinput"
> I can commit a PR to check if this is the cause.

PR welcome!

**Comment by zuozijian3720** [comment] 2023-04-20 14:55
I committed a PR hoping to fix this bug

before this PR:

![Kapture 2023-04-20 at 22 50 32](https://user-images.githubusercontent.com/17165520/233404297-427f9f1d-ad83-4e39-b890-01ec100cfb9a.gif)
after this PR:

![Kapture 2023-04-20 at 22 54 11](https://user-images.githubusercontent.com/17165520/233404904-a030a596-4392-4229-bcae-945d96a40231.gif)

**Closed** 2023-04-21 04:11 UTC
Labels: bug, mod:rich-text, help wanted
