### ISSUE TITLE
To-do list in after indentation Edgeless Mode​

### ISSUE THREAD

**Issue by kemalakcc** [toeverything/blocksuite#5441] opened 2023-11-24 13:59 UTC
### What happened?

As you can see below, after making an indentation on todo list, everything starts to be buggy.

![Peek 2023-11-24 16-54](https://github.com/toeverything/AFFiNE/assets/117591520/33c9dfa3-99f1-4b52-95a1-f043c90fdd2a)

### Distribution version

Linux

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Flrande** [comment] 2023-11-29 07:19
Fixed in #5507

This issue was caused by two simultaneous bugs.

1. The `edgeless-block-portal-container` did not trigger rendering because the passed-in `edgeless` as a property did not change.
https://github.com/toeverything/blocksuite/blob/2c7d451b20ee6d2c5b77eb0d3ab37e5b8b13d9b2/packages/blocks/src/page-block/edgeless/edgeless-page-block.ts#L896-L897

2. The `edgeless-block-portal-note` did not trigger rendering because its self-constructed properties did not change (in doc mode, the `content` changes, but here there is no `content`).
https://github.com/toeverything/blocksuite/blob/2c7d451b20ee6d2c5b77eb0d3ab37e5b8b13d9b2/packages/blocks/src/page-block/edgeless/components/block-portal/edgeless-block-portal.ts#L420-L431

**Closed by Flrande** 2023-11-29 07:19 UTC
Labels: type:bug, mod:list, mod:edgeless, help wanted
