### ISSUE TITLE
Incorrect offset using block slicer in edgeless

### ISSUE THREAD

**Issue by gotjoshua** [toeverything/blocksuite#4255] opened 2023-08-21 10:32 UTC
### What happened?

I split a block once, and then when i want to split it again, the scissors run away from the cursor, so i can never use them to split the block.
It is also a bit mysterious when the scissors icon will show up and in general the mouseover and mousemove handlers need some refinements

### Distribution version

Linux

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment] 2023-08-21 11:49
Hi, this feature is named "block slicer" and it only works for the interval between top-level blocks inside a note. Generally it should work in this way:

https://github.com/toeverything/blocksuite/assets/7312949/2ec419b9-121f-479f-af63-e17b1a720d26

You can see that to use the slicer, you need to select a note and hover to its right edge.

I tried by can't reproduce this issue. Can you reproduce this in [BlockSuite playground](https://blocksuite-toeverything.vercel.app/)?

**Comment by gotjoshua** [comment] 2023-08-21 14:03
[linux beta 0.8.0](https://github.com/toeverything/AFFiNE/releases/download/v0.8.0-beta.0/affine-beta-linux-x64.zip)

its trying to split below a kanban view

**Comment by doodlewind** [comment] 2023-08-21 14:19
I tried splitting after kanban but things seems to work here:

https://github.com/toeverything/blocksuite/assets/7312949/d726a3c1-01bf-4b4d-8372-f5281dfea675

And screen recording would help, thanks.

**Comment by doouding** [comment] 2023-08-22 01:34
This should be fixed but wait for AFFiNE to bump.

**Closed** 2023-08-22 01:52 UTC
Labels: type:bug, reproduction needed, mod:edgeless

**Comment by doouding** [comment] 2023-08-22 01:56
New beta version of AFFiNE has just released, try this out https://github.com/toeverything/AFFiNE/releases/tag/v0.8.0-beta.1
