### ISSUE TITLE
In edgeless mode, if kanban exceeds the length of the screen, it will jump up and down

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#4699] opened 2023-09-11 07:42 UTC

**Comment by zqran** [comment] 2023-09-11 10:06
Reproduction video:

https://github.com/toeverything/blocksuite/assets/15389209/e632c48b-ab3b-4426-973d-2a9bb19f21b4

**Comment by Yuhang1015** [comment] 2023-09-12 06:43
https://github.com/toeverything/blocksuite/assets/142964904/ae254481-fc9f-4d71-85f4-8cfef69b767f

**Comment by zqran** [comment] 2023-09-12 07:48
It doesn’t look like it’s caused by the kanban view of the database. @regischen Please take a look.

**Comment by regischen** [comment] 2023-09-20 03:36
closed by #4738

**Closed by regischen** 2023-09-20 03:36 UTC
Labels: type:bug, mod:edgeless, mod:database
