### ISSUE TITLE
Surface block's children's view position is mismatched with their position in block tree

### ISSUE THREAD

**Issue by Saul-Mirone** [toeverything/blocksuite#5624] opened 2023-12-08 04:53 UTC
For now, surface's children like `image block` is rendered by portal. The portal will render the block in `EdgelessPageBlock`, it will be something like:

```html
<EdgelessPageBlock>
  <SurfaceBlock />
  <Image Portal>
    <Image Block />
  </Image Portal>
</EdgelessPageBlock>
```

The `view` module will calculate the block's position in dom tree and get the `path` for it. So the `path` will be `pageBlock -> imageBlock`.

However, in the block tree in `Yjs`, the structure will be something like:

```js
const blockTree = {
  pageBlock: {
    surfaceBlock: {
      imageBlock: {}
    }
  }
}
```

There'll be a mismatch between model and view.

**Comment by doouding** [comment] 2023-12-13 10:37
Technically, this is not a bug and may not be resolved in the short term. In order to satisfy the product requirements, the image block can only be placed outside the surface for now.
We will discuss possible solutions in the next iteration, though we might stick to the current approach.

**Closed** 2024-03-28 02:33 UTC
Labels: type:bug, mod:edgeless
