### ISSUE TITLE
⚠️ The warning sign emoji is not showing up correctly, it maybe a font-family issue.

### ISSUE THREAD

**Issue by HelloBojack** [toeverything/blocksuite#1111] opened 2023-02-10 06:42 UTC
incorrect:
<img width="441" alt="image" src="https://user-images.githubusercontent.com/39325783/218020373-21783069-2fbe-4d11-aae4-3e73d89ffdeb.png">
correct:
<img width="344" alt="image" src="https://user-images.githubusercontent.com/39325783/218021138-c85ea59c-c22f-4848-87cc-a23817b37b60.png">

**Comment by himself65** [comment] 2023-02-10 07:20
I believe this is not a bug but a feature on different browsers. If you're using macOS. ⚠️ is different on Safari and Chrome.

So I will close this as won't fix it.

**Comment by himself65** [comment] 2023-02-10 07:21
Some websites use svg for the emoji, maybe this could be possible for our editor? 

/cc @doodlewind

**Closed** 2023-02-10 07:43 UTC
