### ISSUE TITLE
node:crypto doesn't exist

### ISSUE THREAD

**Issue by kowtha-sathwik** [toeverything/blocksuite#3529] opened 2023-07-13 14:12 UTC
I am trying to use blocksuite with vanilla js i am getting  node:crypto related error 

error:
[ChildCompiler] ModuleNotFoundError: Module not found: Error: Can't resolve 'node:crypto' in '.../node_modules/lib0'

**Comment by himself65** [comment] 2023-07-13 14:53
Are you using it in node.js environment?

**Comment by fourdim** [comment] 2023-07-13 14:57
Hi, it appears that you are using this repo in a wrong way.
Please follow the document https://blocksuite.affine.pro/getting-started.html to integrate the blocksuite into your project.
Please either use
`pnpm i @blocksuite/editor@nightly`
or
`yarn add @blocksuite/editor@nightly`
or
`npm install @blocksuite/editor@nightly`
according to your package manager to add blocksuite as a dependency in your package.json.
See here for details https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file
By the way, are you new to js?

**Comment by kowtha-sathwik** [comment] 2023-07-13 15:03
> Hi, it appears that you are using this repo in a wrong way. Please follow the document https://blocksuite.affine.pro/getting-started.html to integrate the blocksuite into your project. Please either use `pnpm i @blocksuite/editor@nightly` or `yarn add @blocksuite/editor@nightly` or `npm install @blocksuite/editor@nightly` according to your package manager to add blocksuite as a dependency in your package.json. See here for details https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file By the way, are you new to js?

No i have it in my package.json (as dependence "@blocksuite/editor": "^0.0.0-20230713062147-9eb7708c-nightly")
it is available in my node_modules as well but when i am not able to use it getting this error
i followed below approach 

<img width="769" alt="Screenshot 2023-07-13 at 8 33 33 PM" src="https://github.com/toeverything/blocksuite/assets/137759323/07531b88-7669-4f63-b56b-6fa6bd1c610d">

**Comment by kowtha-sathwik** [comment] 2023-07-13 15:04
> Are you using it in node.js environment?

no

**Comment by fourdim** [comment] 2023-07-13 16:30
Here is a working demo using webpack.
Please compare and check what is wrong.
Source code: [demo.tar.gz](https://github.com/toeverything/blocksuite/files/12041655/demo.tar.gz)

**Comment by doodlewind** [comment] 2023-07-17 16:26
This seems to be related to common Webpack configuration issue, rather than BlockSuite-specific setup. So I'd close this FTM since working example is also provided. But we are also open to build config tweaks if more similar issues are reproduced and reported.

**Closed by doodlewind** 2023-07-17 16:26 UTC
Labels: type:bug, good first issue, compat, help wanted
