### ISSUE TITLE
why does the button of "Insert Button" disappear when I use the branch of canary to develop

### ISSUE THREAD

**Issue by WesternFastShooters** [toeverything/blocksuite#5637] opened 2023-12-10 05:22 UTC
![button_disappear](https://github.com/toeverything/blocksuite/assets/125524146/3eb52b14-dac9-4168-a8bc-b294bc5c9d50)
![localhost_disappear](https://github.com/toeverything/blocksuite/assets/125524146/870c91f8-27ec-4696-a3f8-dc1774bde5ab)

**Comment by doodlewind** [comment] 2023-12-11 12:58
Thanks for your feedback! This is somewhat by design, since we have plan to overhaul the block hub (by possibly moving it to sidebar), and its functionalities can now be covered by slash menu in the doc editor and main toolbar in the edgeless editor.

**Closed by doodlewind** 2023-12-11 12:58 UTC
Labels: type:bug, mod:widget
