### ISSUE TITLE
BlockSuiteError: Missing root model for Doc.

### ISSUE THREAD

**Issue by SoloForge** [toeverything/blocksuite#6506] opened 2024-03-19 04:06 UTC
<img width="824" alt="Screenshot 2024-03-19 at 12 00 32" src="https://github.com/toeverything/blocksuite/assets/153801580/4895e552-081d-4529-b6dd-a389c430402e">

I'm trying to restore data from sqlite db based on this [example](https://github.com/toeverything/blocksuite/tree/master/examples/react-sqlite), however, the docs related to the collection are missing its root model(null). Besides, newly created doc is working fine.

Any suggestion?

**Comment by doodlewind** [comment] 2024-03-19 06:02
Could you share the problematic `.db` file? Thanks.

**Comment by doodlewind** [comment] 2024-03-20 07:08
The [sqlite viewer](https://inloop.github.io/sqlite-viewer/) can be used to inspect the `.db` and you can see it's actually an empty db.

Temporally closing this since it's unable to reproduce and I've verified the SQLite export should work generally (you can type `@...` and enter in doc content to create new docs, and the file size should be ~30KB for multiple docs). Would reopen and keep tracking if you can share the path creating this empty `.db`.

**Closed by doodlewind** 2024-03-20 07:08 UTC
Labels: type:bug, reproduction needed, mod:store
