### ISSUE TITLE
Missing "./themes/affine.css" specifier in "@blocksuite/presets"

### ISSUE THREAD

**Issue by davidkobielski** [toeverything/blocksuite#8796] opened 2024-11-23 03:43 UTC
Hello!
I have Vue app with blocksuite. I want to use editor but I have error with importing css file. Below I pase the error, when I comment this line "import '@blocksuite/presets/themes/affine.css';" the editor is working, just not looking very good, cause of some css lacks.
I would be very grateful for help, thanks!

```
[plugin:vite:import-analysis] Missing "./themes/affine.css" specifier in "@blocksuite/presets" package
Pre-transform error: Missing "./themes/affine.css" specifier in "@blocksuite/presets" package
```

Here is my editor.ts file:
```
import '@blocksuite/presets/themes/affine.css';
import { AffineEditorContainer } from '@blocksuite/presets';
import { Doc, Schema } from '@blocksuite/store';
import { DocCollection } from '@blocksuite/store';
import { AffineSchemas } from '@blocksuite/blocks';

import { effects as blocksEffects } from '@blocksuite/blocks/effects';
import { effects as presetsEffects } from '@blocksuite/presets/effects';

export function initEditor() {

  blocksEffects();
  presetsEffects();
  const schema = new Schema().register(AffineSchemas);
  const collection = new DocCollection({ schema });
  collection.meta.initialize();

  const doc = collection.createDoc({ id: 'page1' });
  doc.load(() => {
    const pageBlockId = doc.addBlock('affine:page', {});
    doc.addBlock('affine:surface', {}, pageBlockId);
    const noteId = doc.addBlock('affine:note', {}, pageBlockId);
    doc.addBlock('affine:paragraph', {}, noteId);
  });

  const editor = new AffineEditorContainer();
  editor.doc = doc;
  return { editor, collection };
}

```

**Comment by miro-ku** [comment] 2024-11-25 08:44
Duplicate of #8451

**Closed** 2024-12-03 04:12 UTC
