### ISSUE TITLE
Inconsistent placement of icon T (Text)

### ISSUE THREAD

**Issue by YanxinLu0122** [toeverything/blocksuite#5057] opened 2023-10-19 02:59 UTC
It would be more cohesive if the text area were slightly narrower and positioned to the right of the icon if it remains on the left.

![Image](https://github.com/toeverything/blocksuite/assets/144991896/e364200b-d2a9-4332-8183-c8ba7e9c2c97)

**Comment by doodlewind** [comment] 2023-10-19 03:45
@hwangdev97 I suppose this is by design?

**Comment by hwangdev97** [comment] 2023-10-20 02:23
Yes, I believe it's by design. cc @zanwei

**Comment by zanwei** [comment] 2023-10-20 02:29
Yes, it's by design. But I think there's potential for enhancement down the road. As of now, it's up to par with our expectations, so I'll be closing this issue

**Closed by zanwei** 2023-10-20 02:29 UTC
Labels: type:bug, mod:database
