### ISSUE TITLE
Connector color doesn't update in toolbar after picking new color

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#3406] opened 2023-07-06 09:08 UTC
https://github.com/toeverything/blocksuite/assets/7312949/38f0aa99-df42-49ab-87e1-327ebe09df2d

inner feedback id: 81

**Comment by regischen** [comment] 2023-07-06 09:15
duplicate of #3344

**Closed by regischen** 2023-07-06 09:15 UTC
Labels: type:bug, mod:edgeless, mod:style
