### ISSUE TITLE
Databases view edit menu ui issues

### ISSUE THREAD

**Issue by u-u-z** [toeverything/blocksuite#5801] opened 2023-12-15 07:22 UTC
### What happened?

when I try to edit my database view

please watch this video 👇

https://github.com/toeverything/AFFiNE/assets/11187239/1249fa85-6ecb-4909-95b5-c1d9cb1abd74

### Distribution version

macOS x64 (Apple Silicon)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zzj3720** [comment] 2023-12-21 02:33
Fixed in https://github.com/toeverything/blocksuite/pull/5522
Not reproduced in canary version

**Comment by doodlewind** [comment] 2023-12-21 02:34
Closing as duplicate of https://github.com/toeverything/blocksuite/issues/5415

**Closed by doodlewind** 2023-12-21 02:34 UTC
Labels: type:bug, mod:database
