### ISSUE TITLE
​Some bugs about tables

### ISSUE THREAD

**Issue by EnterMan123** [toeverything/blocksuite#6832] opened 2024-04-20 19:39 UTC
### What happened?

**1. The CTRL+V paste function cannot be used in the table expansion box**
![1](https://github.com/toeverything/AFFiNE/assets/107846196/5018c4a7-c288-4b95-9185-733384ac8add)

**2. Unable to use CTRL+A to select all text in the table box**
![2](https://github.com/toeverything/AFFiNE/assets/107846196/9c4f2fb7-9822-4612-bc20-8ef45cf13b4b)

**3. When there are too many column types that exceed the width of the table, there is no horizontal scroll bar below**
![5](https://github.com/toeverything/AFFiNE/assets/107846196/9a07162f-98a3-47c5-9b00-b7eedb2838e4)

**4. When there are too many column types, the expansion box overflows**
![4](https://github.com/toeverything/AFFiNE/assets/107846196/094eece3-6405-4639-b30c-6313eb09ec27)

**5. If the column type is text in the expansion box, any content entered will not be reflected in the table**
![6](https://github.com/toeverything/AFFiNE/assets/107846196/0f610918-eb26-49e2-a1e7-4f4d04277445)

**6. The table expansion box looks very crude and does not match the design style of the main program**

### Distribution version

Windows x64

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [ ] Yes

**Comment by golok727** [comment] 2024-04-23 06:16
(2) is closed in https://github.com/toeverything/blocksuite/pull/6570

(3) Is fixed cant find the PR

https://github.com/toeverything/blocksuite/assets/123532141/708aea20-f4fa-42d5-a0d2-c420c86298b4

**Comment by golok727** [comment] 2024-04-23 11:17
(4) https://github.com/toeverything/blocksuite/pull/6851

**Comment by EnterMan123** [comment] 2024-05-05 12:10
@golok727 If the column type is web link or text, the relevant text will not be searched. For example, I have a web link called abcde.com and a text called abcde. I cannot search them. If abcde exists in the title, I can search it.

![1](https://github.com/toeverything/blocksuite/assets/107846196/9c42c318-1f18-4549-92e6-967eaff992d7)
![2](https://github.com/toeverything/blocksuite/assets/107846196/1e872143-3060-4b2d-8bda-ce63fb251546)
![3](https://github.com/toeverything/blocksuite/assets/107846196/78938052-5f46-4765-b979-4b00ae5777f3)
![4](https://github.com/toeverything/blocksuite/assets/107846196/f344adf8-0e2b-407c-acde-b8c99397588b)

**Comment by golok727** [comment] 2024-05-05 18:12
Hey @zzj3720, can content from non-title properties be searched

**Comment by EnterMan123** [comment] 2024-05-10 20:08
7. Unable to continuously input or delete characters of the title in the expansion box
[
![2024-05-11 03-58-32](https://github.com/toeverything/blocksuite/assets/107846196/524209e4-d18b-439f-9e35-79b323083961)
](url)
8. After selecting a date, the date selection box cannot be closed.
![2024-05-11 03-59-02](https://github.com/toeverything/blocksuite/assets/107846196/58a12663-e521-40cb-917d-3cf01b72da72)

9. After I finish typing, sometimes the blue selection box cannot be eliminated.
![2024-05-11 04-00-42](https://github.com/toeverything/blocksuite/assets/107846196/f653ec18-3ef6-478b-9d6c-4eadaa85073c)


@golok727

**Comment by golok727** [comment] 2024-05-11 03:49
> 7. Unable to continuously input or delete characters of the title in the expansion box
>    ![2024-05-11 03-58-32](https://private-user-images.githubusercontent.com/107846196/329707344-2be86af6-762a-448f-a0b5-ff3cd69ae6d5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTk0MTIsIm5iZiI6MTcxNTM5OTExMiwicGF0aCI6Ii8xMDc4NDYxOTYvMzI5NzA3MzQ0LTJiZTg2YWY2LTc2MmEtNDQ4Zi1hMGI1LWZmM2NkNjlhZTZkNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwMzQ1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTNmMDIxNzJjYTM0ZmNiNDUzZGJjOWVhZmZlMGZmNzg2NGI0ZTQxNmZiZWIzZGFkN2M5MTM0YzViNzAwZTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.361C84q9LMFRy3RZx2ukr7CaSK1ZyCdIIGH3Q6Emejw)
>          
>            [
>              
>            
>                ![2024-05-11 03-58-32](https://private-user-images.githubusercontent.com/107846196/329707344-2be86af6-762a-448f-a0b5-ff3cd69ae6d5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTk0MTIsIm5iZiI6MTcxNTM5OTExMiwicGF0aCI6Ii8xMDc4NDYxOTYvMzI5NzA3MzQ0LTJiZTg2YWY2LTc2MmEtNDQ4Zi1hMGI1LWZmM2NkNjlhZTZkNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwMzQ1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTNmMDIxNzJjYTM0ZmNiNDUzZGJjOWVhZmZlMGZmNzg2NGI0ZTQxNmZiZWIzZGFkN2M5MTM0YzViNzAwZTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.361C84q9LMFRy3RZx2ukr7CaSK1ZyCdIIGH3Q6Emejw)
>              ](https://private-user-images.githubusercontent.com/107846196/329707344-2be86af6-762a-448f-a0b5-ff3cd69ae6d5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTk0MTIsIm5iZiI6MTcxNTM5OTExMiwicGF0aCI6Ii8xMDc4NDYxOTYvMzI5NzA3MzQ0LTJiZTg2YWY2LTc2MmEtNDQ4Zi1hMGI1LWZmM2NkNjlhZTZkNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwMzQ1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTNmMDIxNzJjYTM0ZmNiNDUzZGJjOWVhZmZlMGZmNzg2NGI0ZTQxNmZiZWIzZGFkN2M5MTM0YzViNzAwZTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.361C84q9LMFRy3RZx2ukr7CaSK1ZyCdIIGH3Q6Emejw)
>            
>            
>              
>                
>                  
>                
>                
>                  
>                  
>                
>              
>              [
>                
>                  
>                
>              ](https://private-user-images.githubusercontent.com/107846196/329707344-2be86af6-762a-448f-a0b5-ff3cd69ae6d5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTk0MTIsIm5iZiI6MTcxNTM5OTExMiwicGF0aCI6Ii8xMDc4NDYxOTYvMzI5NzA3MzQ0LTJiZTg2YWY2LTc2MmEtNDQ4Zi1hMGI1LWZmM2NkNjlhZTZkNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwMzQ1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTNmMDIxNzJjYTM0ZmNiNDUzZGJjOWVhZmZlMGZmNzg2NGI0ZTQxNmZiZWIzZGFkN2M5MTM0YzViNzAwZTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.361C84q9LMFRy3RZx2ukr7CaSK1ZyCdIIGH3Q6Emejw)
> 8. After selecting a date, the date selection box cannot be closed.
>    ![2024-05-11 03-59-02](https://private-user-images.githubusercontent.com/107846196/329707046-58a12663-e521-40cb-917d-3cf01b72da72.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTk0MTIsIm5iZiI6MTcxNTM5OTExMiwicGF0aCI6Ii8xMDc4NDYxOTYvMzI5NzA3MDQ2LTU4YTEyNjYzLWU1MjEtNDBjYi05MTdkLTNjZjAxYjcyZGE3Mi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwMzQ1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmRiNDAzY2IzZGE0NzgwNmIwNzBiYjVjMTEzZWFiZDdkZDU3ODg1NDdjYTYyYWRhYTMwZWI3NjU2NGJmOWI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FoTW69QynisYOo-GshqrFyWGmH202zaIEaoT_gpIqQg)
>          
>            [
>              
>            
>                ![2024-05-11 03-59-02](https://private-user-images.githubusercontent.com/107846196/329707046-58a12663-e521-40cb-917d-3cf01b72da72.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTk0MTIsIm5iZiI6MTcxNTM5OTExMiwicGF0aCI6Ii8xMDc4NDYxOTYvMzI5NzA3MDQ2LTU4YTEyNjYzLWU1MjEtNDBjYi05MTdkLTNjZjAxYjcyZGE3Mi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwMzQ1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmRiNDAzY2IzZGE0NzgwNmIwNzBiYjVjMTEzZWFiZDdkZDU3ODg1NDdjYTYyYWRhYTMwZWI3NjU2NGJmOWI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FoTW69QynisYOo-GshqrFyWGmH202zaIEaoT_gpIqQg)
>              ](https://private-user-images.githubusercontent.com/107846196/329707046-58a12663-e521-40cb-917d-3cf01b72da72.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTk0MTIsIm5iZiI6MTcxNTM5OTExMiwicGF0aCI6Ii8xMDc4NDYxOTYvMzI5NzA3MDQ2LTU4YTEyNjYzLWU1MjEtNDBjYi05MTdkLTNjZjAxYjcyZGE3Mi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwMzQ1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmRiNDAzY2IzZGE0NzgwNmIwNzBiYjVjMTEzZWFiZDdkZDU3ODg1NDdjYTYyYWRhYTMwZWI3NjU2NGJmOWI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FoTW69QynisYOo-GshqrFyWGmH202zaIEaoT_gpIqQg)
>            
>            
>              
>                
>                  
>                
>                
>                  
>                  
>                
>              
>              [
>                
>                  
>                
>              ](https://private-user-images.githubusercontent.com/107846196/329707046-58a12663-e521-40cb-917d-3cf01b72da72.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTk0MTIsIm5iZiI6MTcxNTM5OTExMiwicGF0aCI6Ii8xMDc4NDYxOTYvMzI5NzA3MDQ2LTU4YTEyNjYzLWU1MjEtNDBjYi05MTdkLTNjZjAxYjcyZGE3Mi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwMzQ1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmRiNDAzY2IzZGE0NzgwNmIwNzBiYjVjMTEzZWFiZDdkZDU3ODg1NDdjYTYyYWRhYTMwZWI3NjU2NGJmOWI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FoTW69QynisYOo-GshqrFyWGmH202zaIEaoT_gpIqQg)
> 9. After I finish typing, sometimes the blue selection box cannot be eliminated.
>    ![2024-05-11 04-10-04 (1)](https://private-user-images.githubusercontent.com/107846196/329708050-7dfd37cc-e017-456b-84ec-1ff97717ef5d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTk0MTIsIm5iZiI6MTcxNTM5OTExMiwicGF0aCI6Ii8xMDc4NDYxOTYvMzI5NzA4MDUwLTdkZmQzN2NjLWUwMTctNDU2Yi04NGVjLTFmZjk3NzE3ZWY1ZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwMzQ1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODY0ZTFlNjQ2MGU3NjBlNGViZjUwOTI2ZTljMWMxZTRiYmQxMmEwNWU5OTVjMmZiODVlMzMyNDYwNGQ4Y2VjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2gCvvyllwT_uHlrEYPnzl2xUVYrZ1OBlq2p-gGcRSvI)
>          
>            [
>              
>            
>                ![2024-05-11 04-10-04 (1)](https://private-user-images.githubusercontent.com/107846196/329708050-7dfd37cc-e017-456b-84ec-1ff97717ef5d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTk0MTIsIm5iZiI6MTcxNTM5OTExMiwicGF0aCI6Ii8xMDc4NDYxOTYvMzI5NzA4MDUwLTdkZmQzN2NjLWUwMTctNDU2Yi04NGVjLTFmZjk3NzE3ZWY1ZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwMzQ1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODY0ZTFlNjQ2MGU3NjBlNGViZjUwOTI2ZTljMWMxZTRiYmQxMmEwNWU5OTVjMmZiODVlMzMyNDYwNGQ4Y2VjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2gCvvyllwT_uHlrEYPnzl2xUVYrZ1OBlq2p-gGcRSvI)
>              ](https://private-user-images.githubusercontent.com/107846196/329708050-7dfd37cc-e017-456b-84ec-1ff97717ef5d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTk0MTIsIm5iZiI6MTcxNTM5OTExMiwicGF0aCI6Ii8xMDc4NDYxOTYvMzI5NzA4MDUwLTdkZmQzN2NjLWUwMTctNDU2Yi04NGVjLTFmZjk3NzE3ZWY1ZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwMzQ1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODY0ZTFlNjQ2MGU3NjBlNGViZjUwOTI2ZTljMWMxZTRiYmQxMmEwNWU5OTVjMmZiODVlMzMyNDYwNGQ4Y2VjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2gCvvyllwT_uHlrEYPnzl2xUVYrZ1OBlq2p-gGcRSvI)
>            
>            
>              
>                
>                  
>                
>                
>                  
>                  
>                
>              
>              [
>                
>                  
>                
>              ](https://private-user-images.githubusercontent.com/107846196/329708050-7dfd37cc-e017-456b-84ec-1ff97717ef5d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTk0MTIsIm5iZiI6MTcxNTM5OTExMiwicGF0aCI6Ii8xMDc4NDYxOTYvMzI5NzA4MDUwLTdkZmQzN2NjLWUwMTctNDU2Yi04NGVjLTFmZjk3NzE3ZWY1ZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwMzQ1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODY0ZTFlNjQ2MGU3NjBlNGViZjUwOTI2ZTljMWMxZTRiYmQxMmEwNWU5OTVjMmZiODVlMzMyNDYwNGQ4Y2VjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2gCvvyllwT_uHlrEYPnzl2xUVYrZ1OBlq2p-gGcRSvI)
> 
> @golok727

Hey, appreciate you flagging these issues. I've managed to replicate them in the playground. I've implemented a temporary workaround for (1), but unfortunately, we had to close it due to some technical constraints. While we work on a permanent solution for the root cause, let's address the remaining issues.

**Comment by golok727** [comment] 2024-05-11 04:01
@EnterMan123, To streamline our bug tracking process, I've created individual issues for each bug, with proper references. Moving forward, let's stick to this method. By creating separate issues for each bug report, we can effectively manage and resolve them. Thank you!

**Closed** 2024-08-17 07:47 UTC
Labels: type:bug, mod:database
