### ISSUE TITLE
Kanban template text disappears at specific node when moving entire whiteboard

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#5681] opened 2023-12-13 06:13 UTC
After adding kanban template to the whiteboard, when moving the entire whiteboard, the text will disappear at a certain node.

https://github.com/toeverything/blocksuite/assets/142964904/5b70f6df-b152-43bb-bcbd-ffaa3bbad47b

**Comment by doouding** [comment] 2023-12-13 10:21
Due to the lack of reproduction, I can only speculate about the cause of the BUG. This might been fixed by [#5685](https://github.com/toeverything/blocksuite/pull/5686). Feel free to reopen this issue if the problem still exists.

**Closed by doouding** 2023-12-13 10:21 UTC
Labels: type:bug, mod:edgeless
