### ISSUE TITLE
Content disappeared in edgeless after toggling right panel

### ISSUE THREAD

**Issue by YanxinLu0122** [toeverything/blocksuite#4777] opened 2023-09-15 08:18 UTC
https://user-images.githubusercontent.com/144991896/268220681-3766642d-f7f4-469b-83ad-c06e2a253ded.mov

**Comment by doodlewind** [comment] 2023-09-16 18:44
Require @doouding to triage (reproduce).

**Comment by doouding** [comment] 2023-09-21 02:34
Can't reproduce it on the latest internal version.

**Comment by doodlewind** [comment] 2023-10-13 04:14
Closing as not reproduced.

**Closed by doodlewind** 2023-10-13 04:14 UTC
Labels: type:bug, reproduction needed, mod:edgeless, fatal
