### ISSUE TITLE
Allow user to specify the index of the first item of a new list other than "1"

### ISSUE THREAD

**Issue by xell** [toeverything/blocksuite#3064] opened 2023-06-12 15:50 UTC
Currently, when I typed a number other than 1 to start a list, the index of this item will be automatically changed to 1. However, I hope the number I typed could be kept as the intentional index number of the first item in the new list.

https://github.com/toeverything/blocksuite/assets/132558/dc2b2590-ed72-4b7c-9f07-a95eab07ab6a

**Comment by doodlewind** [comment] 2023-06-13 01:12
Closing as duplicate of #3008, which indicates better the possible index scope of our ordered list

**Closed** 2023-06-13 01:12 UTC
Labels: mod:list, feat, story
