### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'selection')

### ISSUE THREAD

**Issue by Himself65** [toeverything/blocksuite#425] opened 2022-12-24 01:38 UTC
```bash
TypeError: Cannot read properties of null (reading 'selection')
    at Module.Ji [as getSelectInfo] (index.cb83e548.js?5e3e:793:38)
    at CopyCutManager._getClipItems (copy-cut-manager.js?8022:51:31)
    at CopyCutManager.handleCopy (copy-cut-manager.js?8022:19:1)
    at eval (signal.js?1833:93:1)
    at Array.forEach (<anonymous>)
    at Signal.emit (signal.js?1833:91:1)
    at ClipEventDispatch._copyHandler (clip-event-dispatch.js?f6eb:43:1)
```

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/14026360/209417027-a294c6d5-1fc4-44cc-aa94-2dce65732905.png">

**Comment by doodlewind** [comment] 2023-01-06 00:56
Could you check if you can reproduce this issue? I thought @thorseraq has shipped some selection-related improvement but I can't find it for now.

**Comment by doodlewind** [comment] 2023-01-07 14:29
The cut behavior is refactored in #548 and the selection state is improved in #588. Closing this since it's not reproduced for now (by testing context menu clicks).

**Closed by doodlewind** 2023-01-07 14:29 UTC
Labels: bug, reproduction needed
