### ISSUE TITLE
Incorrect row selection height in database block

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/blocksuite#2815] opened 2023-05-29 03:26 UTC
just look like:

![shot-2023-05-29-11 13 29](https://github.com/toeverything/blocksuite/assets/24713927/88c9a705-3009-4e86-ba25-06524860735d)

**Comment by zqran** [comment] 2023-05-29 07:26
Please confirm here(https://blocksuite-toeverything.vercel.app/?init=database) whether it can be reproduced, if not, it may be because Affine has not been updated to the latest version of BlockSuite.

**Comment by zqran** [comment] 2023-05-29 08:32
fixed by: #2656

**Closed by zqran** 2023-05-29 08:32 UTC
Labels: bug, beta
