### ISSUE TITLE
When dragging the autocomplete arrow with the mouse, the arrow does not follow the mouse

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#4141] opened 2023-08-16 09:57 UTC
https://github.com/toeverything/blocksuite/assets/22443345/4132bfa7-35a5-429f-8504-773a3a3b2afd

**Comment by regischen** [comment] 2023-08-17 02:46
duplicate of #4037

**Closed by regischen** 2023-08-17 02:46 UTC
Labels: type:bug, mod:edgeless
