### ISSUE TITLE
Text Blocks will be merged when being pasted.

### ISSUE THREAD

**Issue by CharlieCho2017** [toeverything/blocksuite#5848] opened 2023-12-25 10:06 UTC
When I copy and paste text. Text Blocks will be merged.

https://github.com/toeverything/blocksuite/assets/28870006/d48a6d4a-b9de-4d5a-a140-da7f6c1e6add

**Comment by fourdim** [comment] 2024-01-08 18:38
Cannot reproduce now. Possibly closed by #5905.

**Closed by fourdim** 2024-01-08 18:38 UTC
Labels: type:bug, mod:clipboard
