### ISSUE TITLE
The selection does not work when scrolling exceeds one screen

### ISSUE THREAD

**Issue by lawvs** [toeverything/blocksuite#5847] opened 2023-12-25 08:13 UTC
The selection does not work when scrolling exceeds one screen.

Related to https://github.com/toeverything/blocksuite/pull/5776

https://github.com/toeverything/blocksuite/assets/18554747/42b5bc0b-dee5-4218-83a1-e8e013db1d8e

**Comment by donteatfriedrice** [comment] 2023-12-25 10:57
There are some other issues:
1. The positions of drag preview and drop indicator are incorrect.
2. The position of TOC highlight mask is incorrect

https://github.com/toeverything/blocksuite/assets/99816898/b877fb68-d07d-4b53-954c-2754190e1bc4

**Comment by AyushAgrawal-A2** [comment] 2023-12-25 11:56
> There are some other issues:
> 
> 1. The positions of drag preview and drop indicator are incorrect.
> 2. The position of TOC highlight mask is incorrect
> 
>  Screen.Recording.2023-12-25.at.18.47.06.mov

I am unable to reproduce these bugs in master...
Please avoid using old deployment links for checking bugs... It wastes everyone's time.

The viewport element was moved in #5776 and any positional computation using `editorHost` / `doc-page-block` as reference will be incorrect.
Let me know if I missed updating any such calculation... 
I have not checked all the features of the app... and it is possible some overlay will be mis-positioned. I will fix them ASAP.

**Comment by donteatfriedrice** [comment] 2023-12-25 12:11
> > There are some other issues:
> > 
> > 1. The positions of drag preview and drop indicator are incorrect.
> > 2. The position of TOC highlight mask is incorrect
> > 
> > Screen.Recording.2023-12-25.at.18.47.06.mov
> 
> @donteatfriedrice I am unable to reproduce these bugs in master... Please avoid using old deployment links for checking bugs... It wastes everyone's time.
> 
> The viewport element was moved in #5776 and any positional computation using `editorHost` / `doc-page-block` as reference will be incorrect. Let me know if I missed updating any such calculation... I have not checked all the features of the app... and it is possible some overlay will be mis-positioned. I will fix them ASAP.

Actually, these bugs still exist in master...

**Comment by donteatfriedrice** [comment] 2023-12-25 12:12
https://github.com/toeverything/blocksuite/assets/99816898/4152174d-67e0-475b-9dac-f140fc49ea46

**Comment by AyushAgrawal-A2** [comment] 2023-12-25 16:51
@donteatfriedrice 
my bad... didn't check after scroll edge cases properly

**Closed** 2023-12-26 01:52 UTC
Labels: type:bug, mod:selection
