### ISSUE TITLE
Unknown super impressive issue

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/blocksuite#5684] opened 2023-12-13 07:15 UTC
https://github.com/toeverything/blocksuite/assets/110808979/6eefa8ea-b157-41d2-a32d-fafe6e8bb06c

**Comment by doouding** [comment] 2023-12-13 10:21
Due to the lack of reproduction, I can only speculate about the cause of the BUG. This might been fixed by [#5685](https://github.com/toeverything/blocksuite/pull/5686). Feel free to reopen this issue if the problem still exists.

**Closed by doouding** 2023-12-13 10:21 UTC
Labels: type:bug, mod:edgeless
