### ISSUE TITLE
Support block-level double-link

### ISSUE THREAD

**Issue by Mojicode** [toeverything/blocksuite#3789] opened 2023-08-01 01:03 UTC
### Description

I have mention the toc in github discussions，it is very usefull，very important.
Block double-link is the same important as page double-link。

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment] 2023-08-02 10:46
Regarding the TOC, it is currently being planned and will be followed up in https://github.com/toeverything/blocksuite/issues/3138 . Please continue to follow it. 

Regarding 'Block double-link', are you referring to bidirectional links? What product are you currently using this feature on?

**Comment by Mojicode** [comment] 2023-08-03 00:59
> Regarding the TOC, it is currently being planned and will be followed up in #3138 . Please continue to follow it.
> 
> Regarding 'Block double-link', are you referring to bidirectional links? What product are you currently using this feature on?

就是块级的双链，现在咱们只支持到页面级的link，就是想问下什么时候对块级的双链进行支持。

**Comment by doodlewind** [comment] 2023-08-03 01:12
We have plan to support block level dual-link in recent release, which is also considered critical in what we envisioned as next-gen editor. But this involves a lot, so the product level release date may be within this year if everything goes fine.

**Comment by Mojicode** [comment] 2023-08-03 01:40
That would be great. Thank you

**Comment by doodlewind** [comment] 2023-10-24 14:26
The ToC part is supported for now, for the block-level link part, it's duplicate of #2268 and let's track there.

**Closed by doodlewind** 2023-10-24 14:26 UTC
Labels: type:feat, mod:link, story
