### ISSUE TITLE
Unable to add block after database block or image block

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#2305] opened 2023-04-26 07:45 UTC

**Comment by zqran** [comment] 2023-04-27 08:13
This problem is not caused by the database. 

For example, inserting a picture in the last line of the document will encounter the same problem.

**Comment by joebeijing** [comment] 2023-04-28 04:07
There are some parts worth discussing:

1. According to the current design, pressing Enter at any position including the title of the last row in the database creates a new row in the database, making it difficult to escape. Even if jumping out is supported, adding a new row in the database after the last row will be exchanged. 

2. Even if the above issue is addressed, the discoverability of this feature is very low, so tools like Notion have added many default behaviors for adding a new row.

For now, if the cost is high, users can be guided to use Block Hub to insert a row anywhere. CC @doodlewind

**Comment by Saul-Mirone** [comment] 2023-04-28 06:52
It's two separate features to me:

1. When the last block is not paragraph block, we need to provide the ability for users to add a paragraph block. Ex, in notion, you can always click to add a paragraph block at the end of the page.
2. When cursor in database block, we need to provide hotkeys for users to exit the block and insert a paragraph block if needed. For example if we have a database block appended by a image block.

As for the schema, I think we should keep it's responsibility simple, which is used to validate data before users make changes to store.

**Comment by zqran** [comment] 2023-04-28 07:25
Close this issue, and use the two separate issues to track: #2360 / #2361 .

**Closed by zqran** 2023-04-28 07:25 UTC
Labels: bug, mod:block-selection
